Task JDP210203-1 is done and package domain with Product and ProductD…
hubert-ros/project-jdp-2102-03 pull request #1
Opened 2021-02-25 18:50 UTC by tomasz-zboralski

…to is created

2021-02-26 10:11 UTC, pablotbg approved these changes

2021-02-27 07:28 UTC, hubert-ros requested changes

2021-02-27 07:28 UTC, hubert-ros commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    public ProductDto getProduct(Long id) {
Najlepiej żeby ten id był przekazywany jako `@PathVariable`

2021-03-01 06:01 UTC, hubert-ros approved these changes

2021-03-01 08:50 UTC, merged

2021-03-01 08:54 UTC, pablotbg commented
O rzesz ty!!! To się da cofnąć. Ja tak nie chciałem, a to poszło na maina.