JDP210203-28 - fixed method in UserController (blockedUser -> blockUser)
hubert-ros/project-jdp-2102-03 pull request #16
Opened 2021-03-04 13:34 UTC by pablotbg

2021-03-04 16:26 UTC, hubert-ros requested changes

2021-03-04 16:26 UTC, hubert-ros commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
>      @PutMapping(value = "blockedUser")
Żeby zmienić endpoint musisz poprawić to w tym miejscu

2021-03-05 17:17 UTC, tomasz-zboralski approved these changes

2021-03-05 20:57 UTC, Arkodiusz approved these changes

2021-03-09 07:14 UTC, hubert-ros approved these changes

2021-03-09 14:55 UTC, merged