Jdp210203 12
hubert-ros/project-jdp-2102-03 pull request #23
Opened 2021-03-10 17:00 UTC by michkubik

2021-03-10 22:30 UTC, Arkodiusz requested changes

2021-03-10 22:30 UTC, Arkodiusz commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
>      private Set<Group> groupsOfProduct = new HashSet<>();
relację z grupą proponuję deklarować po stronie grupy, produkt będzie miał więcej pól wiec dla uproszczenia kodu wystarczy:

    @ManyToMany(mappedBy = "products")
    private Set<Group> groupsOfProduct = new HashSet<>();

powinno działać z moim kodem. Tak samo z relacją z koszykiem.

2021-03-11 12:22 UTC, tomasz-zboralski commented on src/test/java/com/kodilla/ecommercee/EcommerceeApplicationTests.java
> +/*
ja bym usunął ten plik z pull requesta

2021-03-11 12:22 UTC, tomasz-zboralski commented on src/test/java/com/kodilla/ecommercee/SpringBootJPAIntegrationTest.java
> +/*
ten plik też bym usunał z tego pull requesta

2021-03-11 14:01 UTC, Arkodiusz commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +
nie wiem jak testy CircleCi przeszly bez deklaracji relacji w encji Cart :D

Jak coś to ta zmienna (cartOfProduct ) mogłaby nazywać się po prostu 'carts'. Nazwa groupsOfProduct jest tylko ze względu na błędy SQLa jak używałem 'groups'. Decyzja należy do CIebie :)
 
Relacje powinny być OK

2021-03-11 14:01 UTC, Arkodiusz commented on src/main/java/com/kodilla/ecommercee/repository/ProductRepository.java
> +}
albo findAll() albo findById :D
Wyszukiwanie po Id zwróci jeden obiekt typu Product bo Id jest unikalne

findAllByProductName() spoko, choć ja bym nazwę też zmienił na findByName ;)

2021-03-12 23:02 UTC, michkubik commented on src/test/java/com/kodilla/ecommercee/EcommerceeApplicationTests.java
> +/*
OK dzięki!

2021-03-12 23:02 UTC, michkubik commented on src/test/java/com/kodilla/ecommercee/SpringBootJPAIntegrationTest.java
> +/*
OK dzięki!

2021-03-12 23:02 UTC, michkubik commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +
Nazwa zmieniona
Sam nie wiem, jak wyszły - podkreśla mi na czerwono, ale nic się nie dzieje

2021-03-12 23:05 UTC, michkubik commented on src/main/java/com/kodilla/ecommercee/repository/ProductRepository.java
> +}
OK  w sumie racja :)
zmienione

2021-03-13 07:02 UTC, Arkodiusz approved these changes

2021-03-13 08:40 UTC, hubert-ros approved these changes

2021-03-13 09:11 UTC, Arkodiusz commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +
tu jednak lista nie set, nie zauwazulem wcześniej :)

2021-03-13 09:15 UTC, Arkodiusz commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    private Set<Cart> carts = new HashSet<>();
tu jednak musi być lista, ze względu na sposób liczenia ilości w koszyku

2021-03-13 12:13 UTC, Arkodiusz approved these changes

2021-03-14 12:48 UTC, merged