Jdp210203 16
hubert-ros/project-jdp-2102-03 pull request #31
Opened 2021-03-16 20:15 UTC by tomasz-zboralski

Order tests

2021-03-16 23:02 UTC, Arkodiusz approved these changes

2021-03-17 08:31 UTC, hubert-ros approved these changes

2021-03-17 08:35 UTC, hubert-ros requested changes

2021-03-17 08:35 UTC, hubert-ros commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    private String userKey;
Po co jest to pole?

2021-03-17 12:23 UTC, tomasz-zboralski commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    private String userKey;
Usunąłem

2021-03-17 12:47 UTC, hrosinski approved these changes

2021-03-17 12:50 UTC, hubert-ros approved these changes

2021-03-17 13:16 UTC, merged